exclude:
  - README.md

baseurl: /blog

timezone: Europe/London

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins: ['jekyll/scholar']

scholar:
  style: apa-numeric-superscript-brackets
